*************************** 1. row ***************************
       Table: yhf_acc_out_bill
Create Table: CREATE TABLE `yhf_acc_out_bill` (
    `bill_sn` bigint(20) NOT NULL COMMENT '平台账单号（6+6）',
    `his_bill_no` varchar(50) DEFAULT NULL COMMENT 'HIS唯一账单号',
    `his_reg_sn` varchar(30) DEFAULT NULL COMMENT 'HIS就诊号',
    `branch_code` varchar(30) DEFAULT NULL COMMENT '平台机构号，平台授权，需要HIS上传',
    `his_branch_code` varchar(50) DEFAULT NULL,
    `dept_name` varchar(30) DEFAULT NULL COMMENT '科室名称',
    `emp_name` varchar(30) DEFAULT NULL COMMENT '接诊医生姓名',
    `diag` varchar(30) DEFAULT NULL COMMENT '诊断名称',
    `name` varchar(30) NOT NULL COMMENT '病人姓名',
    `id_type` varchar(5) DEFAULT NULL COMMENT '证件类型，01：身份证',
    `id_no` varchar(30) NOT NULL COMMENT '证件号',
    `card_type` varchar(5) DEFAULT NULL COMMENT '就诊卡类型',
    `card_no` varchar(128) DEFAULT NULL COMMENT '就诊卡号',
    `bill_name` varchar(30) DEFAULT NULL COMMENT '账单名称',
    `bill_state` varchar(5) DEFAULT NULL COMMENT '账单状态 00：全部未结算，01：医保已结算',
    `bill_amount` decimal(10,2) DEFAULT NULL COMMENT '账单金额',
    `bill_yb` decimal(10,2) DEFAULT NULL COMMENT '医保已付金额，bill_state为01时有值',
    `bill_discount` decimal(10,2) DEFAULT NULL COMMENT '线下医院已优惠金额',
    `his_bill_date` date NOT NULL COMMENT 'HIS账单时间',
    `his_bill_time` datetime DEFAULT NULL COMMENT 'HIS账单生成时间',
    `pay_type` tinyint(1) DEFAULT NULL COMMENT '支付方式区分=1支付宝、2=微信、3=现金、9=舍入金额',
    `settle_source` tinyint(1) DEFAULT NULL COMMENT '支付方式（1：web端、2：自助机、3：窗口、4：默认自动退款）、5：免密自动支付',
    `pay_state` tinyint(1) NOT NULL DEFAULT '0' COMMENT '支付状态（0未支付、9支付结清）',
    `invalid_state` tinyint(1) NOT NULL DEFAULT '0' COMMENT '作废状态（0未作废、-1作废）',
    `invalid_his_reg_sn` varchar(30) DEFAULT NULL COMMENT '作废HIS唯一账单号',
    `invalid_bill_sn` bigint(20) DEFAULT NULL COMMENT '作废账单号',
    `recharge_bill_sn` bigint(20) DEFAULT NULL COMMENT '重收账单号',
    `invalid_time` datetime DEFAULT NULL COMMENT '作废时间',
    `is_change` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否改账',
    `is_bad` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否坏账0：否，1：是',
    `bill_date` varchar(20) DEFAULT NULL COMMENT '平台账单时间',
    `send_state` tinyint(1) NOT NULL DEFAULT '0' COMMENT '短信催缴状态，1：初始催缴，2：3天催缴，3，7天催缴',
    `pay_time` varchar(30) DEFAULT NULL COMMENT '支付完成时间',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modify_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`bill_sn`),
    KEY `IDX_BILL_BILLSN` (`bill_sn`) USING BTREE,
    KEY `IDX_BILL_NAME_IDNO` (`name`,`id_no`) USING BTREE,
    KEY `IDX_BILL_INVALID_STATE` (`invalid_state`),
    KEY `IDX_HIS_BILL_NO` (`his_bill_no`,`branch_code`) USING BTREE,
    KEY `IDX_BILL_DATE` (`bill_date`) USING BTREE,
    KEY `IDX_BILL_PAY_TIME` (`pay_time`) USING BTREE,
    KEY `IDX_SEND_STATE` (`send_state`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='HIS账单表'